When(/^I am on Appimation home page/) do
  visit('/')
  find(:css, '#start_button')
  find(:xpath, "//button[@id = 'start_button']")
  find(:css, '#signup-b')
  find(:xpath, "//button[@id = 'signup-b']")
  find(:css, '#cta')
  find(:xpath, "//section[@id = 'cta']")
  find(:css, "div[class='idbox']>input[id='name']")
  find(:xpath, "//div[@class='idbox']/input[@id='name']")
  find(:css, "div[class='idbox']>input[id='email']")
  find(:xpath, "//div[@class='idbox']/input[@id='email']")
  find(:css, '#contactus-message')
  find(:xpath, "//textarea[@id = 'contactus-message']")
  find(:css, '#contactus-button')
  find(:xpath, "//input[@id = 'contactus-button']")
  find(:css, "footer[id='footer']>ul[class='icons']>li>a[class='icon fa-facebook']")
  find(:xpath, "//footer[@id='footer']/ul[@class='icons']/li/a[@class='icon fa-facebook']")
  all(:css, "section[class='box special features']>div[class='features-row']>section")
  all(:xpath, "//section[@class='box special features']/div[@class='features-row']/section")
  find(:xpath, "//h3[contains(text(), 'Chain requests with reusable data')]/preceding-sibling::img")
end
